### ISSUE TITLE
ModuleNotFoundError: No module named 'openmixup.models.classifiers.automix_V1plus'

### ISSUE THREAD

**Issue by khawar-islam** [JinXins/Adversarial-AutoMixup#3]
Dear @JinXins 

Thanks for your work and code released. I am running visualization file in your code but it gives lots of error, i have solved some errors but this error is not clear for me.

**(openmixup) cvpr@cvprlab:/media/cvpr/CM_24/Adversarial-AutoMixup$ python3 tools/visualizations/vis_samples.py**
/home/cvpr/anaconda3/envs/openmixup/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(

```
Traceback (most recent call last):
  File "tools/visualizations/vis_samples.py", line 9, in <module>
    from openmixup.models.classifiers.automix_V1plus import *
ModuleNotFoundError: No module named 'openmixup.models.classifiers.automix_V1plus'
```

**Comment by JinXins** [comment]
Dear @khawar-islam, sorry for the late response.

Yes, I checked this project, and this issue came out since in my project we don't include **automix_V1plus.py**, you should download **openmixup** and run this visualization file in openmixup project. 

Hear is the openmixup link : https://github.com/Westlake-AI/openmixup
:)
